apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: dataretrieval
spec:
  template:
    metadata:
      labels:
        app: dataretrieval
    spec:
      containers:
      - image: devengers/dataretrieval
        name: dataretrieval
