apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
apiVersion: v1
kind: Service
metadata:
  name: dataretrieval
  labels:
    app: dataretrieval
spec:
  ports:
  - port: 5002
    targetPort: 5002
  selector:
    app: dataretrieval
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: dataretrieval
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dataretrieval
  template:
    metadata:
      labels:
        app: dataretrieval
    spec:
      containers:
      - image: devengers/dataretrieval
        name: dataretrieval
        ports:
          - containerPort: 5002
