apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    app: ui
spec:
 type: NodePort
 ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 32177
 selector:
  app: ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - image: devengers/ui
        imagePullPolicy: Always
        name: ui
        env:
          - name: REACT_APP_API_URL
            value: "http://um-api"
        ports:
        - containerPort: 3000
