version: '3'

# networks:
#     app-connect:
#         driver : bridge
# networks:
#     session-service-network:
services:
    ui :
        image: devengers/ui
        build : ./Frontend/.
        ports:
            - "0.0.0.0:3000:3000"