version: '3'

# networks:
#     app-connect:
#         driver : bridge
# networks:
#     session-service-network:
services:
    rabbitmq: 
            image: rabbitmq:management
            environment: 
                RABBITMQ_DEFAULT_USER: "guest" 
                RABBITMQ_DEFAULT_PASS: "guest"
            ports:
                - "0.0.0.0:4369:4369"
                - "0.0.0.0:5671:5671"
                - "0.0.0.0:5672:5672"
                - "0.0.0.0:25672:25672"
                - "0.0.0.0:15671:15671"
                - "0.0.0.0:15672:15672"
            healthcheck:
                test: ["CMD", "curl", "-f", "amqp://rabbitmq:5672"]
                interval: 30s
                timeout: 10s
                retries: 5
            # networks:
            #     - app-connect
    sessionservice:
            image : devengers/sessionservice
            build : ./db-service/.
            ports:
            - "0.0.0.0:8300:8300"
            # networks:
            # - session-service-network
            depends_on:
            - mysqldb
    mysqldb:
            image: mysql:8
            ports:
                - '3306:3306'
            # networks:
            # - session-service-network
            environment:
                - MYSQL_ROOT_PASSWORD=IUB@cs123
                - MYSQL_DATABASE=test