version: '3'

# networks:
#     app-connect:
#         driver : bridge
# networks:
#     session-service-network:
services:
    ui :
        image: devengers/ui
        build : ./Frontend/.
        ports:
            - "0.0.0.0:3000:3000"
    mongodb :
        image : mongo
        ports :
            - '0.0.0.0:27017:27017'
    rabbitmq: 
            image: rabbitmq:management
            environment: 
                RABBITMQ_DEFAULT_USER: "guest" 
                RABBITMQ_DEFAULT_PASS: "guest"
            ports:
                - "0.0.0.0:4369:4369"
                - "0.0.0.0:5671:5671"
                - "0.0.0.0:5672:5672"
                - "0.0.0.0:25672:25672"
                - "0.0.0.0:15671:15671"
                - "0.0.0.0:15672:15672"
            healthcheck:
                test: ["CMD", "curl", "-f", "amqp://rabbitmq:5672"]
                interval: 30s
                timeout: 10s
                retries: 5
            # networks:
            #     - app-connect
    um-api :
            image: devengers/um-api
            build : ./Usermanagement_API_Gateway/Backend/.
            environment:
                - HOSTNAMERABBIT=rabbitmq
            ports:
                - "0.0.0.0:8080:8080"
            restart: on-failure
            depends_on:
                - rabbitmq
                - mongodb
            links: 
                - rabbitmq
                - mongodb
                # networks:
                #     - app-connect

    datamodel :
            image: devengers/datamodel
            build : ./datamodelling/.
            environment:
                - HOSTNAMERABBIT=rabbitmq
            depends_on:
                - rabbitmq
                - postgres
            links: 
                - rabbitmq
                - postgres
    dataretrieval:
            image: devengers/dataretrieval
            build : ./dataretrieval/.
            environment:
                - HOSTNAMERABBIT=rabbitmq
            depends_on:
                - rabbitmq
                - postgres
            links: 
                - rabbitmq
                - postgres
    dataanalysis:
            image: devengers/dataanalysis
            build : ./dataanalysis/.
            environment:
                - HOSTNAMERABBIT=rabbitmq
            depends_on:
                - rabbitmq
                - postgres
            links: 
                - rabbitmq
                - postgres
    sessionservice:
            image : devengers/sessionservice
            build : ./db-service/.
            ports:
            - "0.0.0.0:8300:8300"
            # networks:
            # - session-service-network
            depends_on:
            - mysqldb
    mysqldb:
            image: mysql:8
            ports:
                - '3306:3306'
            # networks:
            # - session-service-network
            environment:
                - MYSQL_ROOT_PASSWORD=IUB@cs123
                - MYSQL_DATABASE=test
    postgres:
            image : postgres:11
            ports:
                - "0.0.0.0:5432:5432"
            environment:
                # - POSTGRES_MULTIPLE_DATABASES=dataretrieval_db,datamodelling_db,dataresult_db
                - POSTGRES_USER=postgres
                - POSTGRES_PASSWORD=postgres