apiVersion: v1
kind: Service
metadata:
  name: um-api
spec:
 type: LoadBalancer
 ports:
  - port: 8080
 selector:
  run: um-api
--------  
  apiVersion: v1
kind: Service
metadata:
  name: ui
spec:
 type: NodePort
 ports:
  - port: 3000
 selector:
  run: ui
--------
 apiVersion: v1
kind: Service
metadata:
  name: sessionservice
spec:
 type: NodePort
 ports:
  - port: 8300
 selector:
  run: sessionservice
--------
  apiVersion: v1
kind: Service
metadata:
  name: dataretrieval
spec:
 type: NodePort
 selector:
  run: dataretrieval
--------
  apiVersion: v1
kind: Service
metadata:
  name: datamodel
spec:
 type: NodePort
 selector:
  run: datamodel
--------
  apiVersion: v1
kind: Service
metadata:
  name: dataanalysis
spec:
 type: NodePort
 selector:
  run: dataanalysis
