job('Jenkins-Job-For-Devengers') {
    description("Jenkins job generated by the DSL on ${new Date()}, currently job is generated for Session-Service")
    scm {
        git("https://github.com/airavata-courses/devengers.git", 'develop_new')
    }
    triggers {
        scm('* * * * *')
    }
    steps {
        maven('clean package', 'db-service/pom.xml')
    }
    publishers {
        //archive the war file generated
        archiveArtifacts '**/*.jar'
    }
}
