apiVersion: v1
kind: Service
metadata:
  name: dataanalysis
spec:
 type: NodePort
 selector:
  run: dataanalysis
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: dataanalysis
spec:
  selector:
    matchLabels:
      app: dataanalysis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dataanalysis
    spec:
      containers:
      - image: devengers/dataanalysis
        name: dataanalysis
