apiVersion: v1
kind: Service
metadata:
  name: dataanalysis
  labels:
    app: dataanalysis
spec:
  ports:
  - port: 5004
    targetPort: 5004
  selector:
    app: dataanalysis
---    
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: dataanalysis
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dataanalysis
  template:
    metadata:
      labels:
        app: dataanalysis
    spec:
      containers:
      - image: devengers/dataanalysis
        name: dataanalysis
        ports:
          - containerPort: 5004
