apiVersion: v1
kind: Service
metadata:
  name: datamodel
spec:
 type: NodePort
 selector:
  run: datamodel
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: datamodel
spec:
  template:
    metadata:
      labels:
        app: datamodel
    spec:
      containers:
      - image: devengers/datamodel
        name: datamodel
