apiVersion: v1
kind: Service
metadata:
  name: datamodel
  labels:
    app: datamodel
spec:
  ports:
  - port: 5003
    targetPort: 5003
  selector:
    app: datamodel
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: datamodel
spec:
  replicas: 3
  selector:
    matchLabels:
      app: datamodel
  template:
    metadata:
      labels:
        app: datamodel
    spec:
      containers:
      - image: devengers/datamodel
        name: datamodel
        ports:
          - containerPort: 5003
