apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
 type: NodePort
 ports:
  - port: 5672
 selector:
  run: rabbitmq
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - image: rabbitmq:management
        name: rabbitmq
        env:
          # Use secret in real usage
        ports:
        - containerPort: 5672
          name: rabbitmq