kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongodata-pv
  labels:
    type: local
    app: mongodb
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: mongodb
    io.kompose.service: mongodata
  name: mongodata
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
status: {}