apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
 name: mongo
spec:
 replicas: 1
 serviceName: mongo
 template:
  metadata:
   labels:
    role: mongo
    environment: test
 spec:
  containers:
  - image: mongo
    name: mongo
    ports:
     - containerPort: 27017
    volumeMounts:
     - name: mongo-pv-storage
       mountPath: /data/db
  volumes:
    - name: mongo-pv-storage
      persistentVolumeClaim:
      claimName: mongo-pv-claim
  