apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
 name: mongo
spec:
 replicas: 1
 serviceName: mongo
 template:
  metadata:
   labels:
    role: mongo
    environment: test
  
 spec:
 containers:
  - name: mongo
     image: mongo
     command:
       - mongod
       - "--replSet"
       - rs0
       - "--smallfiles"
       - "--noprealloc"
     ports:
      - containerPort: 27017
     volumeMounts:
      - mountPath: /data/db
      name: mongo-pv-storage
  - name: mongo-sidecar
     image: cvallance/mongo-k8s-sidecar
     env:
      - name: MONGO\_SIDECAR\_POD\_LABELS
        value: "role=mongo,environment=test"
  terminationGracePeriodSeconds: 10 
  volumes:
    - name: mongo-pv-storage
      persistentVolumeClaim:
      claimName: mongo-pv-claims