apiVersion: v1
kind: Service
metadata:
  name: sessionservice
  labels:
    app: sessionservice
spec:
  type: NodePort
  ports:
  - port: 8300
    targetPort: 32179
    nodePort: 32179
  selector:
    app: sessionservice
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: sessionservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sessionservice
  template:
    metadata:
      labels:
        app: sessionservice
    spec:
      containers:
      - image: devengers/sessionservice
        imagePullPolicy: Always
        name: sessionservice
        ports:
        - containerPort: 32179
