apiVersion: v1
kind: Service
metadata:
  name: sessionservice
  labels:
    app: sessionservice
spec:
  ports:
  - protocol: TCP
    port: 8300
    targetPort: 8300
  selector:
    app: sessionservice
  type: ClusterIP
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: sessionservice
spec:
  selector:
    matchLabels:
      app: sessionservice
  template:
    metadata:
      labels:
        app: sessionservice
    spec:
      containers:
      - image: devengers/sessionservice
        name: sessionservice
        ports:
        - containerPort: 8300
          name: sessionservice
