apiVersion: v1
kind: Service
metadata:
  name: sessionservice
spec:
  ports:
  - port: 3306
  selector:
    app: sessionservice
  type: NodePort
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: sessionservice
spec:
  template:
    metadata:
      labels:
        app: sessionservice
    spec:
      containers:
      - image: devengers/sessionservice
        name: sessionservice
        ports:
        - containerPort: 3306
          name: sessionservice
