version: "3"
services:
  session-service:
    image: sessionservice
    ports:
      - "8082:8082"
    networks:
      - session-service-network
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    networks:
      - session-service-network
    environment:
      - MYSQL_ROOT_PASSWORD=IUB@cs123
      - MYSQL_DATABASE=test  

networks:
  session-service-network:
