apiVersion: apps/v1
kind: Deployment
metadata:
  name: um-api
spec:
  template:
    metadata:
      labels:
        app: um-api
    spec:
      containers:
      - image: devengers/um-api
        name: um-api
        env:
        ports:
        - containerPort: 8080
          name: um-api
