apiVersion: v1
kind: Service
metadata:
  name: um-api
  labels:
    app: um-api
spec:
  selector:
    app: um-api
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 32178
    nodePort: 32178
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: um-api
  labels:
    app: um-api
spec:
  replicas: 5
  selector:
    matchLabels:
      app: um-api
  template:
    metadata:
      labels:
        app: um-api
    spec:
      containers:
      - image: devengers/um-api
        imagePullPolicy: Always
        name: um-api
        ports:
        - containerPort: 32178
