apiVersion: apps/v1
kind: Deployment
metadata:
  name: um-api
spec:
  selector:
    matchLabels:
      app: um-api
  template:
    metadata:
      labels:
        app: um-api
    spec:
      containers:
      - image: devengers/um-api
        imagePullPolicy: Always
        name: um-api
        ports:
        - containerPort: 8080